### ISSUE TITLE
Child components can't setState in `componentDidMount`

### ISSUE THREAD

**Issue by giannif** [drcmda/immer-wieder#4]
A child component wrapped with `hoc` can't invoke setState in `componentDidMount` because [this.mounted](https://github.com/drcmda/immer-wieder/blob/master/src/index.js#L44) is false. 

I have a codesandbox demonstrating this, an action is invoked in `componentDidMount`, but the `setState` will not execute.
https://codesandbox.io/s/9zonjjq3k4

If you have any ideas, I'm up for doing a pr. I'm not exactly sure why the `this.mounted` check is required

Great lib though :)

**Comment by drcmda** [comment]
well it is supposed to guard against async setState firing on a dead/unmounted component. It looks like the hoc wants to setState before the inner component is mounted? PRs welcome of course!

**Comment by giannif** [comment]
@drcmda created a PR for this, setting an `unmounted` flag instead of a `mounted` flag, which isn't required for `setState`. I've done `unmounted` to avoid `setState` errors a few times before

**Comment by giannif** [comment]
@drcmda working wonderfully after the patch, thanks!
