### ISSUE TITLE
Is the library Production ready?

### ISSUE THREAD

**Issue by ddennis** [drcmda/immer-wieder#7]
Hi 

Would you consider this llibrary production ready? eg. have you used it in any bigger application?

I also see you have [***react-contextual***](https://github.com/drcmda/react-contextual), would that be a better choice in your opinion? 

Thanks in advanced.

Kind regards
Dennis

**Comment by ddennis** [comment]
Sorry for bumping this. I know you are super busy with react-spring.
But it would be a great help if you have any recommendation on using immer-wieder in a midsize project. Or this is more a proof on concept?

kind regards
Dennis

**Comment by drcmda** [comment]
Github didn't send me notifications :-S this is months too late, but yeah i use it. It's just a small wrap around context so nothing fancy or maintenance heavy.

**Comment by ddennis** [comment]
I know you are busy with React-spring, so thanks for taking the time to answer.
